# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cloudvikingsweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_b5638bb9ea53449d987343aa056d816f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cb587843789e44c1a8173c4ef8781a64 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b5638bb9ea53449d987343aa056d816f }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cloudvikingsweb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_23a38c35c084445580a55c880265b008 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b5638bb9ea53449d987343aa056d816f }}/appsvc/staticsite:${{ github.sha }}'